dist: trusty
sudo: false
language: cpp

addon:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2
